### ISSUE TITLE
"serv status" Value error

### ISSUE THREAD

**Issue by maimon33** [nir0s/serv#2]
serv is adding and removing services properly but status check fails.
Not sure if it's related to specific process or in general

> ubuntu@ip-172-31-26-123:~$ sudo serv status
> INFO - Retrieving status...
> Traceback (most recent call last):
>   File "/usr/local/bin/serv", line 9, in <module>
>     load_entry_point('Serv==0.1.0', 'console_scripts', 'serv')()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/serv/serv.py", line 408, in status
>     status = Serv(init_system, verbose).status(name)
>   File "/usr/local/lib/python2.7/dist-packages/serv/serv.py", line 193, in status
>     return init.status(name)
>   File "/usr/local/lib/python2.7/dist-packages/serv/init/upstart.py", line 53, in status
>     svcs_info = [self._parse_service_info(svc) for svc in svc_list]
>   File "/usr/local/lib/python2.7/dist-packages/serv/init/upstart.py", line 64, in _parse_service_info
>     last_action, status = s[1].split('/')
> ValueError: need more than 1 value to unpack

**Comment by maimon33** [comment]
Found out this doesn't happen on Centos...

> [centos@ip-172-31-32-233 ~]$ sudo serv status vault
> INFO - Retrieving status...
> {
>     "init_system": "systemd", 
>     "init_system_version": "default", 
>     "services": [
>         {
>             "active": "active", 
>             "description": "no", 
>             "load": "loaded", 
>             "name": "vault.service", 
>             "sub": "running"
>         }
>     ]
> }

**Comment by nir0s** [comment]
status is currently broken, as stated in the README. I will be working on it once Serv is stable enough on other fronts and once it supports most major init systems so that I can provide a unified status experience.
